version: "3.8"

services:
  frontend:
    image: nginx:latest
    container_name: blog-frontend_dev
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: development
    container_name: blog-backend_dev
    ports:
      - "4000:4000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello12
      POSTGRES_DB: postgres2
      DB_HOST: database
      PORT: 4000
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:13
    container_name: blog_database_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello12
      POSTGRES_DB: postgres2
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data_dev:
