FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json yarn.lock ./ 
RUN yarn install --production

FROM node:18-alpine AS development
WORKDIR /app
COPY package*.json yarn.lock ./ 
RUN yarn install 

FROM node:18-alpine AS production
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV production

EXPOSE 4000
CMD ["node", "app.js"]
